name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - '**'
      - 'releases/*'
    tags:
      - '!**' # prevent running it for tags  

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm i
      - run: |
          npm run build

  build-test:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      name: setup node
      with:
        node-version: '13.x'

    - name: "install && build"
      run: |
        npm i
        npm run build
    
    - name: "check if build has changed"
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      if: success()
      id: has-changes
      run: |
        ls -las
        git status
        echo "LIB_DIFF=$([[ $(git status -s lib) ]] && echo '1' || echo '')"  >> $GITHUB_ENV
        echo "LIB_DIFF=$([[ $(git status -s lib) ]] && echo '1' || echo '')"
        echo $([[ $(git status -s lib) ]] && echo '1' || echo '')
        echo test1
        echo $GITHUB_ENV
        echo test2

    - name: "Commit files"
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      if: ${{ env.LIB_DIFF }}
      run: |
          echo 'commit files 1'
          echo ${{ env.LIB_DIFF }}
          echo 'commit files 2'
          git config --local user.email "buildaction@bot.bot" 
          git config --local user.name "Build action bot"
          git add .
          git commit -m "build action"
          git status
          git pull
          git status

    - name: "Push changes"
      if: ${{ env.LIB_DIFF }}
      run: |
        git push

  test-after-bot:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo TEST
      - run: |
          ls -las
          ls ./lib -las

  test-with-prefix: 
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          prefix: "/usr/local-test"

  test-without-prefix:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - uses: actions/checkout@v2
      - uses: ./
