name: 'build-test'
on: 
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - '**'
      - 'releases/*'
    tags:
      - '!**' # prevent running it for tags  

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm i
      - run: |
          npm run build

  build-test:
    runs-on: ubuntu-16.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: actions/setup-node@v1
      name: setup node
      with:
        node-version: '13.x'

    - name: build
      run: |
        npm i
        npm run build
        sudo chmod -R 777 ./lib      
    
    - name: check if build has changed
      if: success()
      id: has-changes
      run: |
        ls -las
        git status
        echo "LIB_DIFF=$([[ $(git status -s lib) ]] && echo '1' || echo '')"  >> $GITHUB_ENV

    - name: Commit files
      if: ${{ env.LIB_DIFF }}
      run: |
          git config --local user.email "buildaction@bot.bot" 
          git config --local user.name "Build action bot"
          git add .
          git commit -m "build action"
          git push 

  test:
    needs: build-test
    strategy:
      matrix:
        runs-on: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ubuntu-16.04
    steps:

      - name: Checkout
        uses: actions/checkout@v2
            
      - name: Pull newer source
        run: git pull
      
      - name: Test without prefix
        uses: ./
            
      - name: Test with prefix
        uses: ./
        with:
          prefix: 'usr/local'
