name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - '**'
      - 'releases/*'
    tags:
      - '!**' # prevent running it for tags  

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm i
      - run: |
          npm run build

  build-test:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v1
      name: setup node
      with:
        node-version: '13.x'

    - name: "install && build"
      run: |
        npm i
        npm run build
        sudo chmod -R 777 ./lib      
    
    - name: "check if build has changed"
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      if: success()
      id: has-changes
      run: |
        ls -las
        git status
        echo "LAST_COMMIT=$(git rev-parse HEAD)" >> $GITHUB_ENV
        echo "LIB_DIFF=$([[ $(git status -s lib) ]] && echo '1' || echo '')"  >> $GITHUB_ENV

    - name: "Commit files"
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      if: ${{ env.LIB_DIFF }}
      run: |
          git config --local user.email "buildaction@bot.bot" 
          git config --local user.name "Build action bot"
          git add .
          git commit -m "build action"
          echo "LAST_COMMIT=$(git rev-parse HEAD)" >> $GITHUB_ENV
          echo $LAST_COMMIT
          echo $GITHUB_ENV
          git push 

  test:
    needs: build-test
    runs-on: ubuntu-16.04
    steps:

      # Clone this repo
      - name: Checkout
        uses: actions/checkout@v2
            
      - run: git pull

      # Basic checkout
      - name: Checkout basic
        uses: ./
      
      # Basic checkout with parameter
      - name: Checkout basic
        uses: ./
        with:
          prefix: 'usr/local'

  # test:
  #   needs:
  #   strategy:
  #     matrix:
  #       runs-on: [ubuntu-latest, macos-latest, windows-latest]
  #   runs-on: ${{ matrix.runs-on }}

  #   steps:
  #     # Clone this repo
  #     - name: Checkout
  #       uses: actions/checkout@v2

  #     # Basic checkout
  #     - name: Checkout basic
  #       uses: ./
      
  #     # Basic checkout with parameter
  #     - name: Checkout basic
  #       uses: ./
  #       with:
  #         prefix: 'usr/local'

          